syntax = "proto3";

package identity;

message CreateTenantUserPayload {
  string tenantName = 1;
  string tenantIdentifier = 2;
  string email = 3;
  string name = 4;
  string userType = 5; // "PARTICIPANT" vs.
}

message CreateTenantUserResponse {
  int32 userId = 1;
}

message AccessRequestPayload {
  string email = 1;
  string tenantIdentifier = 2;
}

message AccessRequestResponse {
  string accessUrl = 1;
}

message VerifyAccessCodePayload {
  string code = 1;
}

message VerifyAccessCodeResponse {
  string accessToken = 1;
}

message CreateUserUnderTenantPayload {
  int32 tenantId = 1;
  string name = 2;
  string email = 3;
  string userType = 4;
}

message CreateUserUnderTenantResponse {
  int32 userId = 1;
}

message ListTenantUsersRequest {
  int32 tenantId = 1;
}

message ListTenantUsersResponse {
  repeated IdentityUser users = 1;
}

message IdentityUser {
  int32 id = 1;
  string email = 2;
  string name = 3;
  string type = 4;
  repeated string issues = 5;
}

message DeleteUserPayload {
  int32 userId = 1;
  int32 tenantId = 2;
}

message DeleteUserResponse {
  int32 deletedUserId = 1;
  string userEmail = 2;
  string userType = 3;
}

service IdentityService {
  rpc createTenantAndUser(CreateTenantUserPayload) returns (CreateTenantUserResponse);

  rpc createAccessRequestLink(AccessRequestPayload) returns (AccessRequestResponse);

  rpc verifyAccessCode(VerifyAccessCodePayload) returns (VerifyAccessCodeResponse);

  rpc createUserUnderTenant(CreateUserUnderTenantPayload) returns (CreateUserUnderTenantResponse);

  rpc listTenantUsers(ListTenantUsersRequest) returns (ListTenantUsersResponse);

  rpc deleteUser(DeleteUserPayload) returns (DeleteUserResponse);
}
