syntax = "proto3";

package identity;

import "google/protobuf/timestamp.proto";
import "google/protobuf/empty.proto";

enum TenantIssue {
  NO_PROJECT_FOUND = 0;
  NO_CLIENT_FOUND = 1;
}

enum UserType {
  PARTICIPANT = 0;
  CLIENT = 1;
}

enum UserIssue {
  FIRST_LOGIN_WAS_NOT_MADE = 0;
}


message Tenant {
  int32 id = 1;
  string name = 2;
  string identifier = 3;
  int32 ownerId = 4;
  repeated TenantIssue issues = 5;
  int32 clientsCount = 6;
  int32 participantsCount = 7;
  google.protobuf.Timestamp createdAt = 8;
  google.protobuf.Timestamp updatedAt = 9;
}

message User {
  int32 id = 1;
  int32 tenantId = 2;
  string name = 3;
  string email = 4;
  UserType type = 5;
  repeated UserIssue issues = 6;
  google.protobuf.Timestamp createdAt = 7;
  google.protobuf.Timestamp updatedAt = 8;
}

message TenantWithUsers {
  int32 id = 1;
  string name = 2;
  string identifier = 3;
  int32 ownerId = 4;
  repeated TenantIssue issues = 5;
  int32 clientsCount = 6;
  int32 participantsCount = 7;
  google.protobuf.Timestamp createdAt = 8;
  google.protobuf.Timestamp updatedAt = 9;
  repeated User users = 10;
}

message UserWithTenant {
  int32 id = 1;
  int32 tenantId = 2;
  string name = 3;
  string email = 4;
  UserType type = 5;
  repeated UserIssue issues = 6;
  google.protobuf.Timestamp createdAt = 7;
  google.protobuf.Timestamp updatedAt = 8;
  Tenant tenant = 9;
}


message CreateTenantWithOwnerRequest {
  string tenantName = 1;
  string tenantIdentifier = 2;
  string userName = 3;
  string userEmail = 4;
  UserType userType = 5;
}

message CreateTenantWithOwnerResponse {
  Tenant tenant = 1;
  User user = 2;
}

message AccessRequestPayload {
  string email = 1;
  oneof tenantInfo {
    int32 tenantId = 2;
    string tenantIdentifier = 3;
  }
}

message AccessRequestResponse {
  string accessUrl = 1;
  string accessCode = 2;
  string userName = 3;
  string userType = 4;
  string tenantName = 5;
  string tenantIdentifier = 6;
}

message VerifyAccessRequest {
  string accessCode = 1;
}

message VerifyAccessResponse {
  string accessToken = 1;
}

message CreateUserRequest {
  int32 tenantId = 1;
  string name = 2;
  string email = 3;
  UserType type = 4;
}

message ListUsersRequest {
  int32 tenantId = 1;
}

message ListUsersResponse {
  repeated User users = 1;
}

message GetUserRequest {
  int32 id = 1;
  int32 tenantId = 2;
}

message DeleteUserRequest {
  int32 id = 1;
  int32 tenantId = 2;
}

message DeleteTenantRequest {
  int32 id = 1;
}

message RemoveAccessCodeRequest {
  string accessCode = 1;
}

message RemoveAccessTokenRequest {
  string accessToken = 1;
}

service IdentityService {
  rpc createTenantWithOwner(CreateTenantWithOwnerRequest)
    returns (CreateTenantWithOwnerResponse);

  rpc createAccessRequestLink(AccessRequestPayload)
    returns (AccessRequestResponse);

  rpc verifyAccessCode(VerifyAccessRequest)
    returns (VerifyAccessResponse);

  rpc createUserIfNotExists(CreateUserRequest)
    returns (UserWithTenant);

  rpc listUsers(ListUsersRequest)
    returns (ListUsersResponse);

  rpc getUser(GetUserRequest)
    returns (UserWithTenant);

  rpc deleteUser(DeleteUserRequest)
    returns (UserWithTenant);

  rpc deleteTenant(DeleteTenantRequest)
    returns (TenantWithUsers);

  rpc removeAccessCode(RemoveAccessCodeRequest)
    returns (google.protobuf.Empty);

  rpc removeAccessToken(RemoveAccessTokenRequest)
    returns (google.protobuf.Empty);
}
