syntax = "proto3";

package identity;

import "google/protobuf/timestamp.proto";

service IdentityService {
  rpc createTenantWithOwner(CreateTenantAndUserRequest) returns (CreateTenantAndUserResponse);
  rpc updateTenant(UpdateTenantRequest) returns (GetTenantResponse);
  rpc incrementTenantProjectsCount(IncrementTenantProjectsCountRequest) returns (GetTenantResponse);
  rpc decrementTenantProjectsCount(DecrementTenantProjectsCountRequest) returns (GetTenantResponse);
  rpc deleteTenant(DeleteTenantRequest) returns (GetTenantResponse);

  rpc createUser(CreateUserRequest) returns (GetUserResponse);
  rpc listUsers(ListUsersRequest) returns (ListUsersResponse);
  rpc getUserOrFail(GetUserRequest) returns (GetUserResponse);
  rpc getUser(GetUserRequest) returns (GetUserResponse);
  rpc deleteUser(DeleteUserRequest) returns (GetUserResponse);

  rpc createAccessRequestLink(AccessRequestRequest) returns (AccessRequestResponse);
  rpc verifyAccessCode(VerifyAccessRequest) returns (VerifyAccessResponse);
  rpc removeAccessCode(RemoveAccessCodeRequest) returns (RemoveAccessCodeResponse);
  rpc removeAccessToken(RemoveAccessTokenRequest) returns (RemoveAccessTokenResponse);
}

enum TenantIssue {
  TENANT_ISSUE_UNSPECIFIED = 0;
  NO_PROJECT_FOUND = 1;
  NO_CLIENT_FOUND = 2;
  NO_PARTICIPANT_FOUND = 3;
}

enum UserType {
  USER_TYPE_UNSPECIFIED = 0;
  PARTICIPANT = 1;
  CLIENT = 2;
}

enum UserIssue {
  USER_ISSUE_UNSPECIFIED = 0;
  FIRST_LOGIN_WAS_NOT_MADE = 1;
}

message Tenant {
  int32 id = 1;
  string name = 2;
  string identifier = 3;
  int32 ownerId = 4;
  repeated TenantIssue issues = 5;
  int32 projectsCount = 6;
  int32 clientsCount = 7;
  int32 participantsCount = 8;
  google.protobuf.Timestamp createdAt = 9;
  google.protobuf.Timestamp updatedAt = 10;
  repeated User users = 11;
}

message User {
  int32 id = 1;
  int32 tenantId = 2;
  string name = 3;
  string email = 4;
  UserType type = 5;
  repeated UserIssue issues = 6;
  google.protobuf.Timestamp createdAt = 7;
  google.protobuf.Timestamp updatedAt = 8;

  Tenant tenant = 9;
}

message CreateTenantAndUserRequest {
  TenantInfo tenant = 1;
  UserInfo user = 2;
}

message TenantInfo {
  string name = 1;
  string identifier = 2;
}

message UserInfo {
  string name = 1;
  string email = 2;
  UserType type = 3;
}

message CreateTenantAndUserResponse {
  Tenant tenant = 1;
  User user = 2;
}

message UpdateTenantRequest {
  int32 id = 1;
  string name = 2;
  string identifier = 3;
}

message IncrementTenantProjectsCountRequest {}
message DecrementTenantProjectsCountRequest {}

message DeleteTenantRequest {
  int32 id = 1;
}

message GetTenantResponse {
  Tenant tenant = 1;
}

message CreateUserRequest {
  string name = 1;
  string email = 2;
  UserType type = 3;
}

message ListUsersRequest {
  int32 skip = 1;
  int32 take = 2;
  UserWhereInput where = 3;
}

message GetUserRequest {
  UserWhereInput where = 1;
}

message DeleteUserRequest {
  int32 id = 1;
}

message GetUserResponse {
  User user = 1;
}

message ListUsersResponse {
  int32 totalItemsCount = 1;
  repeated User users = 2;
}

message AccessRequestRequest {
  string email = 1;
  optional int32 tenantId = 2;
  optional string tenantIdentifier = 3;
}

message AccessRequestResponse {
  string accessUrl = 1;
  string accessCode = 2;
  string userName = 3;
  string userType = 4;
  string tenantName = 5;
  string tenantIdentifier = 6;
}

message VerifyAccessRequest {
  string accessCode = 1;
}

message VerifyAccessResponse {
  string accessToken = 1;
}

message RemoveAccessCodeRequest {
  string accessCode = 1;
}

message RemoveAccessCodeResponse {}

message RemoveAccessTokenRequest {
  string accessToken = 1;
}

message RemoveAccessTokenResponse {}

message TenantWhereInput {
  repeated TenantWhereInput AND = 1;
  repeated TenantWhereInput OR = 2;
  repeated TenantWhereInput NOT = 3;

  IntFilter id = 4;
  StringFilter name = 5;
  StringFilter identifier = 6;
  IntFilter ownerId = 7;
  IntFilter projectsCount = 8;
  IntFilter clientsCount = 9;
  IntFilter participantsCount = 10;
  DateTimeFilter createdAt = 11;
  DateTimeFilter updatedAt = 12;
}

message UserWhereInput {
  repeated UserWhereInput AND = 1;
  repeated UserWhereInput OR = 2;
  repeated UserWhereInput NOT = 3;

  IntFilter id = 4;
  IntFilter tenantId = 5;
  StringFilter name = 6;
  StringFilter email = 7;
  EnumUserTypeFilter type = 8;
  DateTimeFilter createdAt = 9;
  DateTimeFilter updatedAt = 10;
}

message IntFilter {
  int32 equals = 1;
  repeated int32 in = 2;
  repeated int32 notIn = 3;
  int32 lt = 4;
  int32 lte = 5;
  int32 gt = 6;
  int32 gte = 7;
  IntFilter not = 8;
}

message StringFilter {
  string equals = 1;
  repeated string in = 2;
  repeated string notIn = 3;
  string lt = 4;
  string lte = 5;
  string gt = 6;
  string gte = 7;
  string contains = 8;
  string startsWith = 9;
  string endsWith = 10;
  StringFilter not = 11;
}

message DateTimeFilter {
  google.protobuf.Timestamp equals = 1;
  repeated google.protobuf.Timestamp in = 2;
  repeated google.protobuf.Timestamp notIn = 3;
  google.protobuf.Timestamp lt = 4;
  google.protobuf.Timestamp lte = 5;
  google.protobuf.Timestamp gt = 6;
  google.protobuf.Timestamp gte = 7;
  DateTimeFilter not = 8;
}

message EnumUserTypeFilter {
  UserType equals = 1;
  repeated UserType in = 2;
  repeated UserType notIn = 3;
  EnumUserTypeFilter not = 4;
}
