syntax = "proto3";

package orchestrator;

import "identity.proto";
import "cms.proto";

service OrchestratorService {
  rpc userRegistrationSaga(identity.CreateTenantAndUserRequest) returns (UserRegistrationSagaResponse);
  rpc userLoginSaga(UserLoginSagaRequest) returns (UserLoginSagaResponse);
  rpc userCreationSaga(identity.CreateUserRequest) returns (identity.GetUserResponse);
  rpc userDeletionSaga(identity.DeleteUserRequest) returns (identity.GetUserResponse);

  rpc addClientsToProjectsSaga(cms.AddClientsToProjectsRequest) returns (cms.ListProjectsResponse);
  rpc removeClientsFromProjectsSaga(cms.RemoveClientsFromProjectsRequest) returns (cms.ListProjectsResponse);

  rpc createProjectSaga(cms.CreateProjectRequest) returns (cms.GetProjectResponse);
  rpc deleteProjectSaga(cms.DeleteProjectRequest) returns (cms.GetProjectResponse);
}

message UserRegistrationSagaResponse {}

message UserLoginSagaRequest {
  string email = 1;
  string identifier = 2;
}

message UserLoginSagaResponse {}
